language: python
python:
 - "3.5"
sudo: required
services:
 - docker
dist: trusty
cache: apt
before_install:
 - docker build -t kismon-travis .travis/
 - docker run -v $PWD:/code/ -d --name kismon-container kismon-travis
script:
 - docker exec kismon-container /usr/bin/python3 -m unittest discover -v
