language: python
python:
 - "3.4"
sudo: required
dist: trusty
cache: apt
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'"
 - "sudo apt-get update"
 - "sudo apt-get -qq install python3-gi python3-cairo python3-simplejson"
 - "sudo apt-get -qq install gir1.2-gtk-3.0 gir1.2-gdkpixbuf-2.0 gir1.2-osmgpsmap-1.0"
script:
 - /usr/bin/python3 -m unittest discover -v
